[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "Eco-Seg"
description = "Smart Annotation Tool"
authors = [
    {name = "Dimitrios Seremetis & Mustafa Bugti", email = "dseremeti@conncoll.edu"},
]
requires-python = ">=3.11"
dependencies = [
    "PyQt5",
    "numpy"
]
version= "1.0.0"

[project.optional-dependencies]
dev = ["pytest"]

[project.scripts]
samat = "src.cli:main"